CREATE DATABASE CADASTROHOTEL;

USE CADASTROHOTEL;

CREATE TABLE SEXO(
    SEX_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    SEX_STR_DESCRICAO CHAR(10),
    CONSTRAINT PK_SEXO_ID PRIMARY KEY(SEX_INT_ID)
);

CREATE TABLE CLIENTE(
    CLI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    SEX_INT_ID INT NOT NULL,
    CLI_STR_RG CHAR(9),
    CLI_STR_NOME VARCHAR(90),
    CLI_STR_TELEFONE CHAR(14),
    CONSTRAINT PK_CLIENTE_ID PRIMARY KEY(CLI_INT_ID),
    CONSTRAINT FK_CLIENTE_SEXO_ID FOREIGN KEY(SEX_INT_ID) REFERENCES SEXO(SEX_INT_ID),
    CONSTRAINT UK_CLIENTE_RG UNIQUE(CLI_STR_RG),
    CONSTRAINT UK_CLIENTE_TELEFONE UNIQUE(CLI_STR_TELEFONE)
);

CREATE TABLE QUARTO(
    QUA_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    QUA_INT_ANDAR INTEGER NOT NULL,
    QUA_STR_TIPO VARCHAR(20) NOT NULL,
    QUA_STR_DESCRICAO VARCHAR(180),
    QUA_FLO_PRECO FLOAT,
    CONSTRAINT PK_QUARTO_ID PRIMARY KEY(QUA_INT_ID)
);

CREATE TABLE OCUPACAO(
    OCU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    QUA_INT_ID INT NOT NULL,
    OCU_DTI_ENTRADA DATETIME,
    OCU_DTI_SAIDA DATETIME,
    CONSTRAINT PK_OCUPACAO_ID PRIMARY KEY(OCU_INT_ID),
    CONSTRAINT FK_OCUPACAO_QUARTO_ID FOREIGN KEY(QUA_INT_ID) REFERENCES QUARTO(QUA_INT_ID)
);

CREATE TABLE RESERVA(
    RES_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    QUA_INT_ID INT NOT NULL,
    CLI_INT_ID INT NOT NULL,
    RES_DAT_DATARESERVA DATE,
    RES_DAT_DATAENTRADA DATE,
    RES_INT_DIASRESERVA INTEGER NOT NULL,
    CONSTRAINT PK_RESERVA_ID PRIMARY KEY(RES_INT_ID),
    CONSTRAINT FK_RESERVA_QUARTO_ID FOREIGN KEY(QUA_INT_ID) REFERENCES QUARTO(QUA_INT_ID),
    CONSTRAINT FK_RESERVA_CLIENTE_ID FOREIGN KEY(CLI_INT_ID) REFERENCES CLIENTE(CLI_INT_ID)
);

CREATE TABLE SERVICO(
    SER_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    OCU_INT_ID INT NOT NULL,
    SER_STR_TIPO VARCHAR(40) NOT NULL,
    SER_STR_DESCRICAO VARCHAR(180),
    SER_FLO_VALORSERVICO FLOAT,
    CONSTRAINT PK_SERVICO_ID PRIMARY KEY(SER_INT_ID),
    CONSTRAINT FK_SERVICO_OCUPACAO_ID FOREIGN KEY(OCU_INT_ID) REFERENCES OCUPACAO(OCU_INT_ID)
);