CREATE DATABASE SISTEMARH;

USE SISTEMARH;

CREATE TABLE DEPARTAMENTO(
    DEP_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    DEP_STR_NOME VARCHAR(90),
    DEP_STR_LOCALIZACAO VARCHAR(150),
    CONSTRAINT PK_DEPARTAMENTO_ID PRIMARY KEY(DEP_INT_ID)
);

CREATE TABLE CARGO(
    CAR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CAR_STR_DESCRICAO VARCHAR(150),
    CONSTRAINT PK_CARGO_ID PRIMARY KEY(CAR_INT_ID)
);

CREATE TABLE SEXO(
    SEX_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    SEX_STR_DESCRICAO CHAR(10),
    CONSTRAINT PK_SEXO_ID PRIMARY KEY(SEX_INT_ID)
);

CREATE TABLE FUNCIONARIO(
    FUN_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    SEX_INT_ID INT NOT NULL,
    CAR_INT_ID INT NOT NULL,
    DEP_INT_ID INT NOT NULL,
    FUN_STR_PRIMEIRONOME VARCHAR(90),
    FUN_STR_ULTIMONOME VARCHAR(90),
    FUN_DAT_DATAADMISSAO DATE,
    FUN_FLO_SALARIO FLOAT NOT NULL,
    FUN_FLO_VALORMCOMISSAO FLOAT,
    CONSTRAINT PK_FUNCIONARIO_ID PRIMARY KEY(FUN_INT_ID),
    CONSTRAINT FK_FUNCIONARIO_SEXO_ID FOREIGN KEY(SEX_INT_ID) REFERENCES SEXO(SEX_INT_ID),
    CONSTRAINT FK_FUNCIONARIO_CARGO_ID FOREIGN KEY(CAR_INT_ID) REFERENCES CARGO(CAR_INT_ID),
    CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO_ID FOREIGN KEY(DEP_INT_ID) REFERENCES DEPARTAMENTO(DEP_INT_ID)
);

CREATE TABLE HISTORICO(
    HIS_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    FUN_INT_ID INT NOT NULL,
    HIS_DAT_ALTERACAO DATE,
    HIS_FLO_SALARIOANTERIOR FLOAT,
    HIS_FLO_NOVOSALARIO FLOAT,
    CONSTRAINT PK_HISTORICO_ID PRIMARY KEY(HIS_INT_ID),
    CONSTRAINT FK_HISTORICO_FUNCIONARIO_ID FOREIGN KEY(FUN_INT_ID) REFERENCES FUNCIONARIO(FUN_INT_ID)
);