CREATE DATABASE VENDAPRODUTO;

USE VENDAPRODUTO;

CREATE TABLE ESTADO (
    EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    EST_STR_DESCRICAO VARCHAR(80)   NOT NULL ,
    EST_STR_SIGLA CHAR(2),
    CONSTRAINT PK_ESTADO_ID PRIMARY KEY(EST_INT_ID),
    CONSTRAINT UK_ESTADO_SIGLA UNIQUE(EST_STR_SIGLA)
);

CREATE TABLE CIDADE (
    CID_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CID_STR_DESCRICAO VARCHAR(90),
    EST_INT_ID INT NOT NULL,
    CONSTRAINT PK_CIDADE_ID PRIMARY KEY(CID_INT_ID),
    CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDERECO (
    END_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_STR_CEP CHAR(8),
    END_STR_LOGRADOURO VARCHAR(50),
    END_STR_NUMERO VARCHAR(10),
    END_STR_COMPLEMENTO VARCHAR(90),
    END_STR_BAIRRO VARCHAR(50),
    CID_INT_ID INT NOT NULL,
    CONSTRAINT PK_ENDERECO_ID PRIMARY KEY(END_INT_ID),
    CONSTRAINT FK_ENDERECO_CIDADE_ID FOREIGN KEY(CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);

CREATE TABLE CLIENTE(
    CLI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_INT_ID INT NOT NULL,
    CLI_STR_NOME VARCHAR(80),
    CLI_STR_IDADE CHAR(3),
    CLI_STR_CPF CHAR(11),
    CLI_STR_EMAIL VARCHAR(90),
    CLI_STR_TELEFONE CHAR(13),
    CONSTRAINT PK_CLIENTE_ID PRIMARY KEY(CLI_INT_ID),
    CONSTRAINT FK_CLIENTE_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
    CONSTRAINT UK_CLIENTE_CPF UNIQUE(CLI_STR_CPF),
    CONSTRAINT UK_CLIENTE_EMAIL UNIQUE(CLI_STR_EMAIL),
    CONSTRAINT UK_CLIENTE_TELEFONE UNIQUE(CLI_STR_EMAIL)
);

CREATE TABLE DEPARTAMENTO(
    DEP_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    DEP_STR_NOME VARCHAR(90),
    DEP_STR_LOCALIZACAO VARCHAR(150),
    CONSTRAINT PK_DEPARTAMENTO_ID PRIMARY KEY(DEP_INT_ID)
);

CREATE TABLE CARGO(
    CAR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CAR_STR_DESCRICAO VARCHAR(150),
    CONSTRAINT PK_CARGO_ID PRIMARY KEY(CAR_INT_ID)
);

CREATE TABLE FUNCIONARIO(
    FUN_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CAR_INT_ID INT NOT NULL,
    DEP_INT_ID INT NOT NULL,
    FUN_STR_NOME VARCHAR(120),
    FUN_STR_CPF CHAR(11),
    FUN_STR_TELEFONE CHAR(13),
    CONSTRAINT PK_FUNCIONARIO_ID PRIMARY KEY(FUN_INT_ID),
    CONSTRAINT FK_FUNCIONARIO_CARGO_ID FOREIGN KEY(CAR_INT_ID) REFERENCES CARGO(CAR_INT_ID),
    CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO_ID FOREIGN KEY(DEP_INT_ID) REFERENCES DEPARTAMENTO(DEP_INT_ID),
    CONSTRAINT UK_FUNCIONARIO_CPF UNIQUE(FUN_STR_CPF),
    CONSTRAINT UK_FUNCIONARIO_TELEFONE UNIQUE(FUN_STR_TELEFONE)
);

CREATE TABLE FORMAPAGAMENTO(
    FPA_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    FPA_STR_DESCRICAO VARCHAR(90),
    CONSTRAINT PK_FORMAPAGAMENTO_ID PRIMARY KEY(FPA_INT_ID),
);

CREATE TABLE VENDA(
    VEN_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    FPA_INT_ID INT NOT NULL,
    FUN_INT_ID INT NOT NULL,
    CLI_INT_ID INT NOT NULL,
    VEN_DTI_DATAVENDA DATETIME,
    VEN_FLO_TOTAL FLOAT,
    CONSTRAINT PK_VENDA_ID PRIMARY KEY(VEN_INT_ID),
    CONSTRAINT FK_VENDA_FORMAPAGAMENTO_ID FOREIGN KEY(FPA_INT_ID) REFERENCES FORMAPAGAMENTO(FPA_INT_ID),
    CONSTRAINT FK_VENDA_FUNCIONARIO_ID FOREIGN KEY(FUN_INT_ID) REFERENCES FUNCIONARIO(FUN_INT_ID),
    CONSTRAINT FK_VENDA_CLIENTE_ID FOREIGN KEY(CLI_INT_ID) REFERENCES CLIENTE(CLI_INT_ID)
);

CREATE TABLE NOTAFISCAL (
    NOF_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    VEN_INT_ID INT NOT NULL,
    NOF_DAT_DATAEMISSAO DATE,
    NOT_FLO_VALORTOTAL FLOAT NOT NULL,
    CONSTRAINT PK_NOTAFISCAL_ID PRIMARY KEY(NOF_INT_ID),
    CONSTRAINT FK_NOTAFISCAL_VENDA_ID FOREIGN KEY(VEN_INT_ID) REFERENCES VENDA(VEN_INT_ID)
);

CREATE TABLE CATEGORIA(
    CAT_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CAT_STR_DESCRICAO VARCHAR(180),
    CONSTRAINT PK_CATEGORIA_ID PRIMARY KEY(CAT_INT_ID)
);

CREATE TABLE MARCA(
    MAR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    MAR_STR_DESCRICAO VARCHAR(180),
    CONSTRAINT PK_MARCA_ID PRIMARY KEY(MAR_INT_ID)
);

CREATE TABLE PRODUTO(
    PRO_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    MAR_INT_ID INT NOT NULL,
    CAT_INT_ID INT NOT NULL,
    PRO_STR_NOME VARCHAR(90),
    PRO_STR_DESCRICAO VARCHAR(180),
    PRO_FLO_PRECO FLOAT,
    PRO_INT_QUANTIDADE INT NOT NULL,
    PRO_FLO_PESO FLOAT,
    CONSTRAINT PK_PRODUTO_ID PRIMARY KEY(PRO_INT_ID),
    CONSTRAINT FK_PRODUTO_MARCA_ID FOREIGN KEY(MAR_INT_ID) REFERENCES MARCA(MAR_INT_ID),
    CONSTRAINT FK_PRODUTO_CATEGORIA_ID FOREIGN KEY(CAT_INT_ID) REFERENCES CATEGORIA(CAT_INT_ID)
);

CREATE TABLE ITEM(
    ITE_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    VEN_INT_ID INT NOT NULL,
    PRO_INT_ID INT NOT NULL,
    ITE_INT_QUANTIDADE INT NOT NULL,
    CONSTRAINT PK_ITEM_ID PRIMARY KEY(ITE_INT_ID),
    CONSTRAINT FK_ITEM_VENDA_ID FOREIGN KEY(VEN_INT_ID) REFERENCES VENDA(VEN_INT_ID),
    CONSTRAINT FK_ITEM_PRODUTO_ID FOREIGN KEY(PRO_INT_ID) REFERENCES PRODUTO(PRO_INT_ID),
);



