CREATE DATABASE CONTROLEESTOQUE;

USE CONTROLEESTOQUE;

CREATE TABLE ESTOQUE(
    EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    EST_STR_DESCRICAO VARCHAR(90),
    CONSTRAINT PK_ESTOQUE_ID PRIMARY KEY(EST_INT_ID)
);

CREATE TABLE FORNECEDOR(
    FOR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    FOR_STR_RAZAOSOCIAL VARCHAR(100),
    FOR_STR_NOMEFANTASIA VARCHAR(80),
    FOR_STR_CNPJ CHAR(14),
    FOR_STR_SITE VARCHAR(90),
    FOR_STR_EMAIL VARCHAR(90),
    FOR_STR_TELEFONE CHAR(15),
    FOR_STR_CONTATO VARCHAR(20),
    CONSTRAINT PK_FORNECEDOR_ID PRIMARY KEY(FOR_INT_ID),
    CONSTRAINT UK_FORNECEDOR_CNPJ UNIQUE(FOR_STR_CNPJ),
    CONSTRAINT UK_FORNECEDOR_SITE UNIQUE(FOR_STR_SITE),
    CONSTRAINT UK_FORNECEDOR_EMAIL UNIQUE(FOR_STR_EMAIL),
    CONSTRAINT UK_FORNECEDOR_TELEFONE UNIQUE(FOR_STR_TELEFONE),
);

CREATE TABLE PRODUTO(
    PRO_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    PRO_STR_NOME VARCHAR(90),
    PRO_FLO_PRECO FLOAT,
    PRO_INT_QUANTIDADE INTEGER,
    CONSTRAINT PK_PRODUTO_ID PRIMARY KEY(PRO_INT_ID)
);

CREATE TABLE PRODUTOFORNECEDOR(
    PRF_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    FOR_INT_ID INT NOT NULL,
    PRO_INT_ID INT NOT NULL,
    CONSTRAINT PK_PRODUTOFORNECEDOR_ID PRIMARY KEY(PRF_INT_ID),
    CONSTRAINT FK_PRODUTOFORNECEDOR_FORNECEDOR_ID FOREIGN KEY(FOR_INT_ID) REFERENCES FORNECEDOR(FOR_INT_ID),
    CONSTRAINT FK_PRODUTOFORNECEDOR_PRODUTO_ID FOREIGN KEY(PRO_INT_ID) REFERENCES PRODUTO(PRO_INT_ID)
);

CREATE TABLE COMPRA(
    COM_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    EST_INT_ID INT NOT NULL,
    CONSTRAINT PK_COMPRA_ID PRIMARY KEY(COM_INT_ID),
    CONSTRAINT FK_COMPRA_ESTOQUE_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTOQUE(EST_INT_ID)
);

CREATE TABLE COMPRAPRODUTO(
    COP_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    COM_INT_ID INT NOT NULL,
    PRO_INT_ID INT NOT NULL,
    CONSTRAINT PK_COMPRAPRODUTO_ID PRIMARY KEY(COP_INT_ID),
    CONSTRAINT FK_COMPRAPRODUTO_COMPRA_ID FOREIGN KEY(COM_INT_ID) REFERENCES COMPRA(COM_INT_ID),
    CONSTRAINT FK_COMPRAPRODUTO_PRODUTO_ID FOREIGN KEY(PRO_INT_ID) REFERENCES PRODUTO(PRO_INT_ID)
);

