CREATE DATABASE SITESOLUCAOINFORMATICA;

USE SITESOLUCAOINFORMATICA;

CREATE TABLE ESTADO (
    EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    EST_STR_DESCRICAO VARCHAR(80)   NOT NULL ,
    EST_STR_SIGLA CHAR(2),
    CONSTRAINT PK_ESTADO_ID PRIMARY KEY(EST_INT_ID),
    CONSTRAINT UK_ESTADO_SIGLA UNIQUE(EST_STR_SIGLA)
);

CREATE TABLE CIDADE (
    CID_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CID_STR_DESCRICAO VARCHAR(90),
    EST_INT_ID INT NOT NULL,
    CONSTRAINT PK_CIDADE_ID PRIMARY KEY(CID_INT_ID),
    CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDERECO (
    END_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_STR_CEP CHAR(8),
    END_STR_LOGRADOURO VARCHAR(50),
    END_STR_NUMERO VARCHAR(10),
    END_STR_COMPLEMENTO VARCHAR(90),
    END_STR_BAIRRO VARCHAR(50),
    EST_INT_ID INT NOT NULL,
    CID_INT_ID INT NOT NULL,
    CONSTRAINT PK_ENDERECO_ID PRIMARY KEY(END_INT_ID),
    CONSTRAINT FK_ENDERECO_ESTADO_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID),
    CONSTRAINT FK_ENDERECO_CIDADE_ID FOREIGN KEY(CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);

CREATE TABLE USUARIO(
    USU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_INT_ID INT NOT NULL,
    USU_STR_NOME VARCHAR(90),
    USU_STR_EMAIL VARCHAR(90),
    USU_STR_TELEFONE CHAR(13),
    CONSTRAINT PK_USUARIO_ID PRIMARY KEY(USU_INT_ID),
    CONSTRAINT FK_USUARIO_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
    CONSTRAINT UK_USUARIO_TELEFONE UNIQUE(USU_STR_TELEFONE),
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE(USU_STR_EMAIL)
);

CREATE TABLE PLATAFORMA(
    PLA_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    PLA_STR_DESCRICAO VARCHAR(20),
    CONSTRAINT PK_PLATAFORMA_ID PRIMARY KEY(PLA_INT_ID)
);

CREATE TABLE AREAINTERESSE(
    ARE_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    ARE_STR_DESCRICAO VARCHAR(30),
    CONSTRAINT PK_AREAINTERESSE_ID PRIMARY KEY(ARE_INT_ID)
);

CREATE TABLE CONSULTOR(
    COS_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_INT_ID INT NOT NULL,
    COS_STR_NOME VARCHAR(50),
    COS_STR_TELEFONE CHAR(13),
    CONSTRAINT PK_CONSULTOR_ID PRIMARY KEY(COS_INT_ID),
    CONSTRAINT FK_CONSULTOR_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
    CONSTRAINT UK_CONSULTOR_TELEFONE UNIQUE(COS_STR_TELEFONE)
);

CREATE TABLE EVENTO(
    EVE_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    COS_INT_ID INT NOT NULL,
    ARE_INT_ID INT NOT NULL,
    USU_INT_ID INT NOT NULL,
    PLA_INT_ID INT NOT NULL,
    EVE_DAT_DATAEVENTO DATE,
    EVE_STR_SOLUCAO VARCHAR(90),
    EVE_STR_PROBLEMA VARCHAR(90),
    CONSTRAINT PK_EVENTO_ID PRIMARY KEY(EVE_INT_ID),
    CONSTRAINT FK_EVENTO_CONSULTOR_ID FOREIGN KEY(COS_INT_ID) REFERENCES CONSULTOR(COS_INT_ID),
    CONSTRAINT FK_EVENTO_AREAINTERESSE_ID FOREIGN KEY(ARE_INT_ID) REFERENCES AREAINTERESSE(ARE_INT_ID),
    CONSTRAINT FK_EVENTO_USUARIO_ID FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID),
    CONSTRAINT FK_EVENTO_PLATAFORMA_ID FOREIGN KEY(PLA_INT_ID) REFERENCES PLATAFORMA(PLA_INT_ID)
);

CREATE TABLE COMENTARIO(
    COM_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    EVE_INT_ID INT NOT NULL,
    USU_INT_ID INT NOT NULL,
    COM_STR_DESCRICAO VARCHAR(300),
    CONSTRAINT PK_COMENTARIO_ID PRIMARY KEY(COM_INT_ID),
    CONSTRAINT FK_COMENTARIO_EVENTO_ID FOREIGN KEY(EVE_INT_ID) REFERENCES EVENTO(EVE_INT_ID),
    CONSTRAINT FK_COMENTARIO_USUARIO_ID FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID),
);