CREATE DATABASE PROJETOENGENHARIA;

USE PROJETOENGENHARIA;

CREATE TABLE CARGO(
    CAR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CAR_STR_DESCRICAO VARCHAR(90),
    CONSTRAINT PK_CARGO_ID PRIMARY KEY(CAR_INT_ID)
);

CREATE TABLE PROJETO(
    PRO_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    PRO_STR_NOME VARCHAR(90),
    PRO_DAT_INICIO DATE,
    PRO_DAT_TERMINO DATE,
    PRO_STR_DESCRICAO VARCHAR(200),
    CONSTRAINT PK_PROJETO_ID PRIMARY KEY(PRO_INT_ID)
);

CREATE TABLE FUNCIONARIO(
    FUN_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CAR_INT_ID INT NOT NULL,
    FUN_STR_NOME VARCHAR(90),
    FUN_STR_IDADE CHAR(3),
    FUN_STR_CPF CHAR(11),
    FUN_STR_RG CHAR(9),
    FUN_FLO_SALARIO FLOAT,
    FUN_STR_EMAIL VARCHAR(90),
    FUN_STR_TELEFONE CHAR(13),
    CONSTRAINT PK_FUNCIONARIO_ID PRIMARY KEY(FUN_INT_ID),
    CONSTRAINT FK_FUNCIONARIO_CARGO_ID FOREIGN KEY(CAR_INT_ID) REFERENCES CARGO(CAR_INT_ID), 
    CONSTRAINT UK_FUNCIONARIO_CPF UNIQUE(FUN_STR_CPF),
    CONSTRAINT UK_FUNCIONARIO_RG UNIQUE(FUN_STR_RG),
    CONSTRAINT UK_FUNCIONARIO_EMAIL UNIQUE(FUN_STR_EMAIL),
    CONSTRAINT UK_FUNCIONARIO_TELEFONE UNIQUE(FUN_STR_TELEFONE)
);

CREATE TABLE ALOCACAO(
    ALO_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    FUN_INT_ID INTEGER NOT NULL,
    PRO_INT_ID INT NOT NULL,
    ALO_DAT_INICIOATIVIDADE DATE,
    ALO_INT_MESES INTEGER,
    CONSTRAINT PK_ALOCACAO_ID PRIMARY KEY(ALO_INT_ID),
    CONSTRAINT FK_ALOCACAO_FUNCIONARIO_ID FOREIGN KEY(FUN_INT_ID) REFERENCES FUNCIONARIO(FUN_INT_ID),
    CONSTRAINT FK_ALOCACAO_PROJETO_ID FOREIGN KEY(PRO_INT_ID) REFERENCES PROJETO(PRO_INT_ID)
);

