CREATE DATABASE AEROCLUBE;

USE AEROCLUBE;

CREATE TABLE ESTADO (
    EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    EST_STR_DESCRICAO VARCHAR(80)   NOT NULL ,
    EST_STR_SIGLA CHAR(2),
    CONSTRAINT PK_ESTADO_ID PRIMARY KEY(EST_INT_ID),
    CONSTRAINT UK_ESTADO_SIGLA UNIQUE(EST_STR_SIGLA)
);

CREATE TABLE CIDADE (
    CID_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CID_STR_DESCRICAO VARCHAR(90),
    EST_INT_ID INT NOT NULL,
    CONSTRAINT PK_CIDADE_ID PRIMARY KEY(CID_INT_ID),
    CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDERECO (
    END_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_STR_CEP CHAR(8),
    END_STR_LOGRADOURO VARCHAR(50),
    END_STR_NUMERO VARCHAR(10),
    END_STR_COMPLEMENTO VARCHAR(90),
    END_STR_BAIRRO VARCHAR(50),
    CID_INT_ID INT NOT NULL,
    CONSTRAINT PK_ENDERECO_ID PRIMARY KEY(END_INT_ID),
    CONSTRAINT FK_ENDERECO_CIDADE_ID FOREIGN KEY(CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);

CREATE TABLE PILOTO(
    PIL_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_INT_ID INT NOT NULL,
    PIL_STR_NOME VARCHAR(90),
    PIL_INT_IDADE INT NOT NULL,
    PIL_STR_NUMEROBREVE VARCHAR(10),
    CONSTRAINT PK_PILOTO_ID PRIMARY KEY(PIL_INT_ID),
    CONSTRAINT FK_PILOTO_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
    CONSTRAINT UK_PILOTO_NUMEROBREVE UNIQUE(PIL_STR_NUMEROBREVE)
);

CREATE TABLE CURSO(
    CUR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CUR_STR_DESCRICAO VARCHAR(100),
    CUR_STR_INSTITUICAO VARCHAR(190),
    CUR_DAT_DIPLOMA DATE,
    CONSTRAINT PK_CURSO_ID PRIMARY KEY(CUR_INT_ID)
);

CREATE TABLE INSTRUTOR(
    INS_INT_IDMATRICULA INTEGER NOT NULL IDENTITY(1,1),
    END_INT_ID INT NOT NULL,
    CUR_INT_ID INT NOT NULL,
    INS_STR_NOME VARCHAR(90),
    INS_INT_IDADE INT NOT NULL, 
    INS_STR_NUMEROBREVE VARCHAR(10),
    CONSTRAINT PK_INSTRUTOR_IDMATRICULA PRIMARY KEY(INS_INT_IDMATRICULA),
    CONSTRAINT FK_INSTRUTOR_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
    CONSTRAINT FK_INSTRUTOR_CURSO_ID FOREIGN KEY(CUR_INT_ID) REFERENCES CURSO(CUR_INT_ID)
);

CREATE TABLE ALUNO(
    ALU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_INT_ID INT NOT NULL,
    ALU_STR_NOME VARCHAR(90),
    ALU_INT_IDADE INT NOT NULL, 
    ALU_TIM_HORASVOO TIME,
    CONSTRAINT PK_ALUNO_ID PRIMARY KEY(ALU_INT_ID),
    CONSTRAINT FK_ALUNO_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID)
);

CREATE TABLE SAIDA(
    SAI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    ALU_INT_ID INT NOT NULL,
    INS_INT_IDMATRICULA INT NOT NULL,
    SAI_DAT_DATASAIDA DATE,
    SAI_TIM_HORASAIDA TIME,
    SAI_TIM_HORACHEGADA TIME,
    SAI_STR_PARECERINSTRUTOR VARCHAR(200),
    CONSTRAINT PK_SAIDA_ID PRIMARY KEY(SAI_INT_ID),
    CONSTRAINT FK_SAIDA_ALUNO_ID FOREIGN KEY(ALU_INT_ID) REFERENCES ALUNO(ALU_INT_ID),
    CONSTRAINT FK_SAIDA_INSTRUTOR_ID FOREIGN KEY(INS_INT_IDMATRICULA) REFERENCES INSTRUTOR(INS_INT_IDMATRICULA)
);