CREATE DATABASE CONTROLEACADEMIA;

USE CONTROLEACADEMIA;

CREATE TABLE ESTADO (
    EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    EST_STR_DESCRICAO VARCHAR(80) NOT NULL ,
    EST_STR_SIGLA CHAR(2),
    CONSTRAINT PK_ESTADO_ID PRIMARY KEY(EST_INT_ID),
    CONSTRAINT UK_ESTADO_SIGLA UNIQUE(EST_STR_SIGLA)
);

CREATE TABLE CIDADE (
    CID_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CID_STR_DESCRICAO VARCHAR(90),
    EST_INT_ID INT NOT NULL,
    CONSTRAINT PK_CIDADE_ID PRIMARY KEY(CID_INT_ID),
    CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDERECO (
    END_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_STR_CEP CHAR(8),
    END_STR_LOGRADOURO VARCHAR(50),
    END_STR_NUMERO VARCHAR(10),
    END_STR_COMPLEMENTO VARCHAR(90),
    END_STR_BAIRRO VARCHAR(50),
    CID_INT_ID INT NOT NULL,
    CONSTRAINT PK_ENDERECO_ID PRIMARY KEY(END_INT_ID),
    CONSTRAINT FK_ENDERECO_CIDADE_ID FOREIGN KEY(CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);

CREATE TABLE ATIVIDADE(
    ATI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    ATI_STR_DESCRICAO VARCHAR(90) NOT NULL,
    CONSTRAINT PK_ATIVIDADE_ID PRIMARY KEY(ATI_INT_ID)
);

CREATE TABLE INSTRUTOR(
    INS_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    INS_STR_RG CHAR(9),
    INS_STR_NOME VARCHAR(90),
    INS_DAT_DATANASCIMENTO DATE,
    INS_STR_TITULACAO VARCHAR(120),
    CONSTRAINT PK_INSTRUTOR_ID PRIMARY KEY(INS_INT_ID),
    CONSTRAINT UK_INSTRUTOR_RG UNIQUE(INS_STR_RG)
);

CREATE TABLE TELEFONE(
    TEL_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    TEL_STR_NUMEROTELEFONE CHAR(14), 
    TEL_STR_CONTATO VARCHAR(50),
    INS_INT_ID INT NOT NULL,
    CONSTRAINT PK_TELEFONE_ID PRIMARY KEY(TEL_INT_ID),
    CONSTRAINT FK_TELEFONE_INSTRUTOR_ID FOREIGN KEY(INS_INT_ID) REFERENCES INSTRUTOR(INS_INT_ID)
);

CREATE TABLE TURMA(
    TUR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    INS_INT_ID INT NOT NULL,
    ATI_INT_ID INT NOT NULL,
    TUR_INT_QUANTIDADEALUNO INT NOT NULL,
    TUR_TIM_HORARIO TIME,
    TUR_TIM_DURACAO TIME,
    TUR_DAT_DATAINICIAL DATE,
    TUR_DAT_DATAFINAL DATE,
    CONSTRAINT PK_TURMA_ID PRIMARY KEY(TUR_INT_ID),
    CONSTRAINT FK_TURMA_INSTRUTOR_ID FOREIGN KEY(INS_INT_ID) REFERENCES INSTRUTOR(INS_INT_ID),
    CONSTRAINT FK_TURMA_ATIVIDADE_ID FOREIGN KEY(ATI_INT_ID) REFERENCES ATIVIDADE(ATI_INT_ID)
);

CREATE TABLE ALUNO(
    ALU_INT_IDMATRICULA INTEGER NOT NULL IDENTITY(1,1),
    END_INT_ID INT NOT NULL,
    ALU_DAT_DATAMATRICULA DATE,
    ALU_STR_NOME VARCHAR(90),
    ALU_STR_TELEFONE CHAR(14),
    ALU_DAT_DATANASCIMENTO DATE,
    ALU_FLO_ALTURA FLOAT,
    ALU_FLO_PESO FLOAT,
    CONSTRAINT PK_ALUNO_ID PRIMARY KEY(ALU_INT_IDMATRICULA),
    CONSTRAINT FK_ALUNO_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID),
    CONSTRAINT UK_ALUNO_TELEFONE UNIQUE(ALU_STR_TELEFONE)
);

CREATE TABLE MATRICULA(
    MAT_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    ALU_INT_IDMATRICULA INT NOT NULL,
    TUR_INT_ID INT NOT NULL,
    MAT_INT_AUSENCIA INT,
    CONSTRAINT PK_MATRICULA_ID PRIMARY KEY(MAT_INT_ID),
    CONSTRAINT FK_MATRICULA_ALUNO_ID FOREIGN KEY(ALU_INT_IDMATRICULA) REFERENCES ALUNO(ALU_INT_IDMATRICULA),
    CONSTRAINT FK_MATRICULA_TURMA_ID FOREIGN KEY(TUR_INT_ID) REFERENCES TURMA(TUR_INT_ID)
);

CREATE TABLE MONITOR(
    MON_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    ALU_INT_IDMATRICULA INT NOT NULL,
    TUR_INT_ID INT NOT NULL,
    CONSTRAINT PK_MONITOR_ID PRIMARY KEY(MON_INT_ID),
    CONSTRAINT FK_MONITOR_ALUNO_ID FOREIGN KEY(ALU_INT_IDMATRICULA) REFERENCES ALUNO(ALU_INT_IDMATRICULA),
    CONSTRAINT FK_MONITOR_TURMA_ID FOREIGN KEY(TUR_INT_ID) REFERENCES TURMA(TUR_INT_ID)
);