CREATE DATABASE TREINAMENTOTECNICO;

USE TREINAMENTOTECNICO;

CREATE TABLE INSTRUTOR(
    INS_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    INS_INT_NOME VARCHAR(90),
    INS_STR_TELEFONE CHAR(13),
    CONSTRAINT PK_INSTRUTOR_ID PRIMARY KEY(INS_INT_ID),
    CONSTRAINT UK_INSTRUTOR_TELEFONE UNIQUE(INS_STR_TELEFONE)
);

CREATE TABLE CURSO(
    CUR_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    INS_INT_ID INT NOT NULL,
    CUR_STR_CODIGO VARCHAR(30),
    CUR_STR_NOME VARCHAR(60),
    CUR_FLO_PRECO FLOAT NOT NULL,
    CUR_INT_DIASDURACAO INTEGER NOT NULL,
    CONSTRAINT PK_CURSO_ID PRIMARY KEY(CUR_INT_ID),
    CONSTRAINT FK_CURSO_INSTRUTOR_ID FOREIGN KEY(INS_INT_ID) REFERENCES INSTRUTOR(INS_INT_ID)
);

CREATE TABLE ALUNO(
    ALU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    ALU_STR_NOME VARCHAR(90),
    ALU_STR_TELEFONE CHAR(13),
    CONSTRAINT PK_ALUNO_ID PRIMARY KEY (ALU_INT_ID),
    CONSTRAINT UK_ALUNO_TELEFONE UNIQUE(ALU_STR_TELEFONE)
);

CREATE TABLE ALUNOCURSO(
    ALC_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    ALU_INT_ID INT NOT NULL,
    CUR_INT_ID INT NOT NULL,
    CONSTRAINT PK_ALUNOCURSO_ID PRIMARY KEY(ALC_INT_ID),
    CONSTRAINT FK_ALUNOCURSO_ALUNO_ID FOREIGN KEY(ALU_INT_ID) REFERENCES ALUNO(ALU_INT_ID),
    CONSTRAINT FK_ALUNOCURSO_CURSO_ID FOREIGN KEY(CUR_INT_ID) REFERENCES CURSO(CUR_INT_ID)
);