CREATE DATABASE CATALOGOCD;

USE CATALOGOCD;

CREATE TABLE ESTADO (
    EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    EST_STR_DESCRICAO VARCHAR(80)   NOT NULL ,
    EST_STR_SIGLA CHAR(2),
    CONSTRAINT PK_ESTADO_ID PRIMARY KEY(EST_INT_ID),
    CONSTRAINT UK_ESTADO_SIGLA UNIQUE(EST_STR_SIGLA)
);

CREATE TABLE CIDADE (
    CID_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CID_STR_DESCRICAO VARCHAR(90),
    EST_INT_ID INT NOT NULL,
    CONSTRAINT PK_CIDADE_ID PRIMARY KEY(CID_INT_ID),
    CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
);

CREATE TABLE ENDERECO (
    END_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_STR_CEP CHAR(8),
    END_STR_LOGRADOURO VARCHAR(50),
    END_STR_NUMERO VARCHAR(10),
    END_STR_COMPLEMENTO VARCHAR(90),
    END_STR_BAIRRO VARCHAR(50),
    CID_INT_ID INT NOT NULL,
    CONSTRAINT PK_ENDERECO_ID PRIMARY KEY(END_INT_ID),
    CONSTRAINT FK_ENDERECO_CIDADE_ID FOREIGN KEY(CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
);

CREATE TABLE GRAVADORA(
    GRA_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    GRA_STR_RAZAOSOCIAL VARCHAR(100),
    GRA_STR_NOMEFANTASIA VARCHAR(80),
    GRA_STR_CNPJ CHAR(14),
    GRA_STR_SITE VARCHAR(90),
    GRA_STR_EMAIL VARCHAR(90),
    GRA_STR_TELEFONE CHAR(15),
    GRA_STR_CONTATO VARCHAR(20),
    END_INT_ID INT NOT NULL,
    CONSTRAINT PK_GRAVADORA_ID PRIMARY KEY(GRA_INT_ID),
    CONSTRAINT UK_GRAVADORA_CNPJ UNIQUE(GRA_STR_CNPJ),
    CONSTRAINT UK_GRAVADORA_SITE UNIQUE(GRA_STR_SITE),
    CONSTRAINT UK_GRAVADORA_EMAIL UNIQUE(GRA_STR_EMAIL),
    CONSTRAINT UK_GRAVADORA_TELEFONE UNIQUE(GRA_STR_TELEFONE),
    CONSTRAINT FK_GRAVADORA_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID)
);

CREATE TABLE FORMAPAGAMENTO(
    FPA_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    FPA_STR_DESCRICAO VARCHAR(90),
    CONSTRAINT PK_FORMAPAGAMENTO_ID PRIMARY KEY(FPA_INT_ID),
);

CREATE TABLE PEDIDOCOMPRA(
    PCO_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    GRA_INT_ID INT NOT NULL,
    FPA_INT_ID INT NOT NULL,
    CONSTRAINT PK_PEDIDOCOMPRA_ID PRIMARY KEY(PCO_INT_ID),
    CONSTRAINT FK_PEDIDOCOMPRA_GRAVADORA_ID FOREIGN KEY(GRA_INT_ID) REFERENCES GRAVADORA(GRA_INT_ID),
    CONSTRAINT FK_PEDIDOCOMPRA_FORMAPAGAMENTO_ID FOREIGN KEY(FPA_INT_ID) REFERENCES FORMAPAGAMENTO(FPA_INT_ID)
);

CREATE TABLE CLIENTE(
    CLI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    END_INT_ID INT NOT NULL,
    CLI_STR_NOME VARCHAR(80),
    CLI_STR_IDADE CHAR(3),
    CLI_STR_CPF CHAR(11),
    CLI_STR_EMAIL VARCHAR(90),
    CLI_STR_TELEFONE CHAR(13),
    CONSTRAINT PK_CLIENTE_ID PRIMARY KEY(CLI_INT_ID),
    CONSTRAINT FK_CLIENTE_ENDERECO_ID FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID)
);

CREATE TABLE PEDIDOVENDA(
    PVE_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    FPA_INT_ID INT NOT NULL,
    CLI_INT_ID INT NOT NULL,
    CONSTRAINT PK_PEDIDOVENDA_ID PRIMARY KEY(PVE_INT_ID),
    CONSTRAINT FK_PEDIDOVENDA_FORMAPAGAMENTO_ID FOREIGN KEY(FPA_INT_ID) REFERENCES FORMAPAGAMENTO(FPA_INT_ID),
    CONSTRAINT FK_PEDIDOVENDA_CLIENTE_ID FOREIGN KEY(CLI_INT_ID) REFERENCES CLIENTE(CLI_INT_ID)
);

CREATE TABLE GENEROMUSICAL(
    GEN_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    GEN_STR_DESCRICAO VARCHAR(90),
    CONSTRAINT PK_GENEROMUSICAL_ID PRIMARY KEY(GEN_INT_ID)
);

CREATE TABLE MUSICA(
    MUS_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    GEN_INT_ID INT NOT NULL,
    MUS_STR_DESCRICAO VARCHAR(90),
    MUS_STR_INTERPRETE VARCHAR(90),
    MUS_STR_COMPOSITOR VARCHAR(90),
    MUS_TIM_DURACAO TIME,
    CONSTRAINT PK_MUSICA_ID PRIMARY KEY(MUS_INT_ID),
    CONSTRAINT FK_MUSICA_GENEROMUSICAL_ID FOREIGN KEY(GEN_INT_ID) REFERENCES GENEROMUSICAL(GEN_INT_ID)
);

CREATE TABLE INTERPRETE(
    ITP_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    ITP_STR_DESCRICAO VARCHAR(90),
    CONSTRAINT PK_INTERPRETE_ID PRIMARY KEY(ITP_INT_ID)
);

CREATE TABLE COMPOSITOR(
    COM_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    COM_STR_DESCRICAO VARCHAR(90),
    CONSTRAINT PK_COMPOSITOR_ID PRIMARY KEY(COM_INT_ID)
);

CREATE TABLE MUSICAINTERPRETE(
    MIP_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    MUS_INT_ID INT NOT NULL,
    ITP_INT_ID INT NOT NULL,
    CONSTRAINT PK_MUSICAINTERPRETE_ID PRIMARY KEY(MIP_INT_ID),
    CONSTRAINT FK_MUSICAINTERPRETE_MUSICA_ID FOREIGN KEY(MUS_INT_ID) REFERENCES MUSICA(MUS_INT_ID),
    CONSTRAINT FK_MUSICAINTERPRETE_INTERPRETE_ID FOREIGN KEY(ITP_INT_ID) REFERENCES INTERPRETE(ITP_INT_ID)
);

CREATE TABLE MUSICACOMPOSITOR(
    MCO_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    MUS_INT_ID INT NOT NULL,
    COM_INT_ID INT NOT NULL,
    CONSTRAINT PK_MUSICACOMPOSITOR_ID PRIMARY KEY(MCO_INT_ID),
    CONSTRAINT FK_MUSICACOMPOSITOR_MUSICA_ID FOREIGN KEY(MUS_INT_ID) REFERENCES MUSICA(MUS_INT_ID),
    CONSTRAINT FK_MUSICACOMPOSITOR_COMPOSITOR_ID FOREIGN KEY(COM_INT_ID) REFERENCES COMPOSITOR(COM_INT_ID)
);

CREATE TABLE CD(
    CD_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    CD_STR_DESCRICAO VARCHAR(90),
    CD_REA_PRECO REAL,
    CD_INT_QUANTIDADEMUSICA INTEGER NOT NULL,
    GRA_INT_ID INT NOT NULL,
    MUS_INT_ID INT NOT NULL,
    CONSTRAINT PK_CD_ID PRIMARY KEY(CD_INT_ID),
    CONSTRAINT FK_CD_GRAVADORA_ID FOREIGN KEY(GRA_INT_ID) REFERENCES GRAVADORA(GRA_INT_ID),
    CONSTRAINT FK_CD_MUSICA_ID FOREIGN KEY(MUS_INT_ID) REFERENCES MUSICA(MUS_INT_ID)
);

CREATE TABLE PEDIDOCOMPRACD(
    PCC_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    PCO_INT_ID INT NOT NULL,
    CD_INT_ID INT NOT NULL,
    CONSTRAINT PK_PEDIDOCOMPRACD_ID PRIMARY KEY(PCC_INT_ID),
    CONSTRAINT FK_PEDIDOCOMPRACD_PEDIDOCOMPRA_ID FOREIGN KEY(PCO_INT_ID) REFERENCES PEDIDOCOMPRA(PCO_INT_ID),
    CONSTRAINT FK_PEDIDOCOMPRACD_CD_ID FOREIGN KEY(CD_INT_ID) REFERENCES CD(CD_INT_ID)
);

CREATE TABLE PEDIDOVENDACD(
    PVC_INT_ID INTEGER NOT NULL IDENTITY(1,1),
    PVE_INT_ID INT NOT NULL,
    CD_INT_ID INT NOT NULL,
    CONSTRAINT PK_PEDIDOVENDACD_ID PRIMARY KEY(PVC_INT_ID),
    CONSTRAINT FK_PEDIDOVENDACD_PEDIDOVENDA_ID FOREIGN KEY(PVE_INT_ID) REFERENCES PEDIDOVENDA(PVE_INT_ID),
    CONSTRAINT FK_PEDIDOVENDACD_CD_ID FOREIGN KEY(CD_INT_ID) REFERENCES CD(CD_INT_ID)
);



